name: Publish tweet when gas info changes
on:
  push:
    paths:
      - "gas_info.json"
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - name: Install project requirements
        run: pip install -r requirements.txt
      - name: Publish tweet with gas prices
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python tweet.py
      - name: Save last gas prices
        run: python add_history.py
      - name: Commit gas history information
        run: |
          git config --global user.name 'Dntfreitas'
          git config --global user.email 'dntfreitas123@gmail.com'
          git add gas_info_history.json
          git diff-index --quiet HEAD || git commit -m "update gas history information"
          git push
