name: Extract data from DRTT
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - name: Install project requirements
        run: pip install -r requirements.txt
      - name: Export data to file
        run: python script.py > gas_info.json
      - name: Commit gas information
        run: |
          git config --global user.name 'Dntfreitas'
          git config --global user.email 'Dntfreitas@users.noreply.github.com'
          git add gas_info.json
          git commit -m "Updated information"
