name: Extract data from DRTT
on:
  schedule:
    - cron: '0 */6 * * *'
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - name: Install project requirements
        run: pip install -r requirements.txt
      - name: Export data to file
        run: python script.py > gas_info.json
      - name: Commit gas information
        run: |
          git config --global user.name 'Dntfreitas'
          git config --global user.email 'dntfreitas123@gmail.com'
          git add gas_info.json
          git diff-index --quiet HEAD || git commit -m "Update gas information"
          git push
